
name: 'gcp_dbt_demo'
version: '1.0.0'
config-version: 2

profile: 'gcp_dbt_demo'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  gcp_dbt_demo:
    +materialized: view
    staging:
      +materialized: table
    marts:
      +materialized: view
