
gcp_dbt_demo:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: fast-archive-470501-a3
      dataset: demo_dbt
      threads: 4
      keyfile: /Users/adamjones/Documents/git/data_demo/gcp.json
      location: US
