
name: dbt-ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-bigquery
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery

      - name: Create service account key file
        run: |
          printf '%s' "${{ secrets.GCP_SA_KEY }}" > gcp.json

      - name: Create dbt profiles.yml
        run: |
          mkdir -p dbt/profiles
          cat > dbt/profiles/profiles.yml << EOF
          gcp_dbt_demo:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: ${{ secrets.GCP_PROJECT_ID }}
                dataset: ${{ secrets.DBT_DATASET }}
                threads: 4
                keyfile: ${{ github.workspace }}/gcp.json
                location: ${{ secrets.GCP_LOCATION }}
          EOF

      - name: Run dbt build
        working-directory: dbt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp.json
        run: |
          dbt deps
          dbt build --profiles-dir ./profiles
